### ISSUE TITLE
Cannot insert a new value in HashMap.insert()

### ISSUE THREAD

**Issue by OmkarPathak** [paulmouzas/paulmouzas.github.io#1]
While inserting a new Key Value pair in your HashMap class, the for loop (line marked with >) doesn't get executed because the bucket is returning an empty list.
```python
def insert(self, key, value):
        hash_key = hash(key) % len(self.hashmap)
        key_exists = False
        bucket = self.hashmap[hash_key]
        

      > for i, kv in enumerate(bucket):

            k, v = kv
            if key == k:
                key_exists = True
                break
        if key_exists:
            bucket[i] = ((key, value))
        else:
            bucket.append((key,value))
```
This causes for loop to not execute even once.

**Comment by paulmouzas** [comment]
Yes. It doesn't need to if the bucket is empty. It will always be empty the first time around. If you insert objects in the map that yield the same hash_key then the loop will execute because there are items in the bucket. The loop does not need to run if the bucket is empty.
